### PR TITLE
Solve issue #4

### LINKED ISSUE #4: Can start a Round with 0 Players
# Problem
Right now the Bot allows you to configure a Round to have 0 Players and 0 Roles, which should not happen a this just simply does not make any sense at all

# Solution
Before transitioning from the RegisterUsers state to the next State, we should check for the Player count to be greater than 0 and otherwise return an appropriate Error

### PR DESCRIPTION
**Pull request by kiennguyenchi**
Solve Issue #4 
Hi there, please kindly take a look at my revision and give me any feedback. Thank you!

### CODE REVIEW

**Review by Lol3rrr — CHANGES_REQUESTED** [review]
These Notes in the Code need to be addressed however the idea is definetly correct.

I would also say that your logic should be moved from this function to the impl block `impl TryTransition<RoundState<RegisterUsers>> for RoundState<RegisterRoles>` and more specifically the `try_transition` function (line 300-330) as that is the place where we would lock in the Players and move on to the next Stage of starting a Round.

In that function you should also return an error instead of directly outputting it using tracing, you might also need to add a new Error type, but first I would change the aformentioned parts

**Review by Lol3rrr — CHANGES_REQUESTED** [review]
There are now only a couple of minor changes but nothing major and from the logic it should definetly be correct

**Review by Lol3rrr — CHANGES_REQUESTED** [review]
Only that one small problem is still left

**Review by Lol3rrr — CHANGES_REQUESTED** [review]
Sorry, this was my mistake and I should have seen this earlier but the String or &str Type in Rust does not implement the `std::error::Error` Trait which is needed to turn it into a TransitionError.

The easy fix for this would be to create a simple NewType that wraps the String and this type then implements the `std::error::Error` trait.

Example:
This would be outside the impl Block
```
pub struct StringError(String);

impl std::fmt::Debug for StringError {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
    write!(f, "{:?}", self.0)
  }
}
impl std::fmt::Display for StringError {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
    write!(f, "{}", self.0)
  }
}
impl std::error::Error for StringError {}
```

This could then be used as a TransitionError like so:
```
TransitionError::new(StringError("your string content".to_string()))
```

**Review by Lol3rrr — APPROVED** [review]
This now all looks fine to me and should work

**Comment by kiennguyenchi** [comment]
I really appreciate your support!

**Pull request merged**
